#!/usr/bin/env php
<?php
declare(strict_types = 1);

if (is_file(__DIR__ . '/../../autoload.php')) {
	require_once __DIR__ . '/../../autoload.php';
}

Phar::loadPhar(__DIR__ . '/phpcs.phar', 'phpcs.phar');
require_once 'phar://phpcs.phar/autoload.php';

Spaze\PHPCSPhar\StandardsInstaller::install();
$status = (new PHP_CodeSniffer\Runner())->runPHPCBF();
exit($status);
