name: Create a phar release

on:
  schedule:
    - cron: "16 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Fetch latest phar"
      id: fetch_phar
      run: |-
        release=$(gh release view --repo PHPCSStandards/PHP_CodeSniffer --json tagName,name)
        version=$(echo "$release" | jq -r '.tagName')
        name=$(echo "$release" | jq -r '.name')
        gh release download --repo PHPCSStandards/PHP_CodeSniffer --tag "$version" --pattern "phpcs.phar" --pattern "phpcs.phar.asc" --dir ./ --clobber
        delimiter=$(openssl rand -hex 8)
        {
          echo "version<<${delimiter}"
          echo "${version}"
          echo "${delimiter}"
          echo "name<<${delimiter}"
          echo "${name}"
          echo "${delimiter}"
        } >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "Verify GPG signature"
      run: |-
        gpg --no-default-keyring --keyring trustedkeys.kbx --keyserver hkps://keyserver.ubuntu.com --receive-keys 689DAD778FF08760E046228BA978220305CD5C32 D91D86963AF3A29B6520462297B02DD8E5071466
        gpgv phpcs.phar.asc phpcs.phar
    - name: "Fetch phpcs.xsd"
      run: wget --timestamping https://github.com/PHPCSStandards/PHP_CodeSniffer/raw/${{ steps.fetch_phar.outputs.version }}/phpcs.xsd
    - name: "Update replaced versions in composer.json"
      run: jq --tab '.replace["phpcsstandards/php_codesniffer","squizlabs/php_codesniffer"] |= "${{ steps.fetch_phar.outputs.version }}"' composer.json > composer.json.new && mv composer.json.new composer.json
    - name: "Commit and push any modified files"
      id: commit_push
      run: |-
        git config user.name "Automated release"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Release ${{ steps.fetch_phar.outputs.version }}" || exit 0
        git push
        echo "release=true" >> $GITHUB_OUTPUT
    - name: "Smoke test"
      if: success() && steps.commit_push.outputs.release
      run: |-
        composer update
        ./phpcs --version
        ./phpcbf --version
    - name: "Create release ${{ steps.fetch_phar.outputs.version }}"
      if: success() && steps.commit_push.outputs.release
      run: gh release create ${{ steps.fetch_phar.outputs.version }} --title "${{ steps.fetch_phar.outputs.name }}" --notes "Find the release notes for version ${{ steps.fetch_phar.outputs.version }} [here](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/${{ steps.fetch_phar.outputs.version }})."
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
